### ISSUE TITLE
Missing Key Annotation

### ISSUE THREAD

**Issue by PierreColombo** [WebNLG/challenge-2020#2]
Hello,
Thanks for releasing the data the annotation **_1124_** for the Baseline-FORGE2020 seems to be missing. 
Maybe a wrong parsing ?
Kindest regards

**Comment by nilinykh** [comment]
@PierreColombo the issue is with the annotations in https://github.com/WebNLG/challenge-2020/blob/main/evaluation/human-evaluation/results/en/Baseline-FORGE2020/primary.json, right?

I can see that human scores for `1124` are indeed not available. They are not in the file because we did not include some of the items in our recollection of human scores.

If you look at our [challenge report](https://www.aclweb.org/anthology/2020.webnlg-1.7.pdf) (page 8, middle of the left-hand column), it says the following:
`
For English data, we identified 21 bad annotators, submitting around 25% of all data for English evaluation. We recollected 20% of these annotations, ensuring that their quality is reliable, and removed the other 5% of data from the results.
`

It turns out, human scores for this particular item for this specific submission were among this 5%, for which we did not re-collect new human scores. For now, I updated this file with `1124={}`. Please consider that if you cannot find *any* annotations for some of the items, you need to ignore those since there are no human annotations for them.
